name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    name: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Docker build
        run: docker build -t ghcr.io/ducc/bristle:$GITHUB_SHA -f Dockerfile .
        
      - name: Docker login
        run: echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login ghcr.io -u ducc --password-stdin
    
      - name: Docker push
        run: docker push ghcr.io/ducc/bristle:$GITHUB_SHA
